### ISSUE TITLE
constraints for background image

### ISSUE THREAD

**Issue by rhjordaan** [Ramotion/paper-onboarding#123]
Hi, I'm trying to add a background image that takes up the whole screen in my onboarding. So far this code adds the image, but it isn't scaled and shifted properly to fit the whole screen. Would you mind helping me with this? Thanks a lot in advance. This is in the onboardingConfigurationItem function.

`
func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {

        let backgroundImages = [UIImageView(image: #imageLiteral(resourceName: "Main Screen")),UIImageView(image: #imageLiteral(resourceName: "Main Screen")),UIImageView(image: #imageLiteral(resourceName: "onboarding2")),UIImageView(image: #imageLiteral(resourceName: "onboarding2"))]
        
        
        // assume you have an array of uiimages
        let imgView = backgroundImages[index]
            
        imgView.translatesAutoresizingMaskIntoConstraints = false
        item.insertSubview(imgView, at: 0)

            
        imgView.contentMode = .scaleToFill
 
}

`

**Comment by igork-ramotion** [comment]
@rhjordaan Hey!) Currently Paper Onboarding doesn't support this feature, but you can hack it for example like this. 

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            guard let w = UIApplication.shared.delegate?.window else { return }
            
            let imgView = UIView()
            imgView.backgroundColor = [UIColor.yellow, UIColor.red, UIColor.green][index]
            imgView.translatesAutoresizingMaskIntoConstraints = false
            item.insertSubview(imgView, at: 0)
            
            let f = item.superview?.convert(item.frame, to: w) ?? .zero
            imgView.frame = CGRect(x: 0, y: -f.minY, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)
        }
```

I think you will want to remove delay to make appearance looks better, in that case you should adjust vertical offset manually. This happen because when delegate method is calling  paper onboarding, control is not in views hierarchy, so you can't layout it properly. 

I'm not recommend you to use this solution, I provide it just to illustrate internal processes.
You can fork this repo and add new delegate method to change item background, it will be much better solution

**Comment by rhjordaan** [comment]
thank you!
